# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "NSDate-RelativeTime" do

end

target "NSDate-RelativeTimeTests" do
  pod 'NSDate-RelativeTime', path: '../'
  pod 'Kiwi/XCTest'
end

